# Generated by Django 5.2.5 on 2025-08-10 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofaclogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 10, 11, 23, 21, 837028, tzinfo=datetime.timezone.utc)),
        ),
    ]
